// <auto-generated />
using System;
using ComputerShopDataBaseImplement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComputerShopDataBaseImplement.Migrations
{
    [DbContext(typeof(ComputerShopDataBase))]
    partial class ComputerShopDataBaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ComputerShopDataBaseImplement.Models.Complect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ComplectId")
                        .HasColumnType("int");

                    b.Property<string>("ComplectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostavshikId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ComplectId")
                        .IsUnique()
                        .HasFilter("[ComplectId] IS NOT NULL");

                    b.HasIndex("PostavshikId");

                    b.ToTable("Complects");
                });

            modelBuilder.Entity("ComputerShopDataBaseImplement.Models.ComplectPolTechnic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ComplectId")
                        .HasColumnType("int");

                    b.Property<int>("PolTechnicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComplectId");

                    b.HasIndex("PolTechnicId");

                    b.ToTable("ComplectPolTechnics");
                });

            modelBuilder.Entity("ComputerShopDataBaseImplement.Models.PolTechnic", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatePos")
                        .HasColumnType("datetime2");

                    b.Property<string>("PolTechnicName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostavkaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PolTechnics");
                });

            modelBuilder.Entity("ComputerShopDataBaseImplement.Models.Postavka", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("PostavkaCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostavkaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZakupkaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Postavkas");
                });

            modelBuilder.Entity("ComputerShopDataBaseImplement.Models.Postavshik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Postavshiks");
                });

            modelBuilder.Entity("ComputerShopDataBaseImplement.Models.Sborka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PostavshikId")
                        .HasColumnType("int");

                    b.Property<string>("SborkaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PostavshikId");

                    b.ToTable("Sborkas");
                });

            modelBuilder.Entity("ComputerShopDataBaseImplement.Models.SborkaComplect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ComplectId")
                        .HasColumnType("int");

                    b.Property<int>("SborkaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComplectId");

                    b.HasIndex("SborkaId");

                    b.ToTable("SborkaComplects");
                });

            modelBuilder.Entity("ComputerShopDataBaseImplement.Models.SborkaZaiavka", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SborkaId")
                        .HasColumnType("int");

                    b.Property<int>("ZaiavkaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SborkaId");

                    b.HasIndex("ZaiavkaId");

                    b.ToTable("SborkaZaiavkas");
                });

            modelBuilder.Entity("ComputerShopDataBaseImplement.Models.Zaiavka", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ZaiavkaName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zaiavkas");
                });

            modelBuilder.Entity("ComputerShopDataBaseImplement.Models.Zakupka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ComplectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateBuy")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostavshikId")
                        .HasColumnType("int");

                    b.Property<int?>("ZakupkaId")
                        .HasColumnType("int");

                    b.Property<string>("ZakupkaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PostavshikId");

                    b.HasIndex("ZakupkaId")
                        .IsUnique()
                        .HasFilter("[ZakupkaId] IS NOT NULL");

                    b.ToTable("Zakupkas");
                });

            modelBuilder.Entity("ComputerShopDataBaseImplement.Models.Complect", b =>
                {
                    b.HasOne("ComputerShopDataBaseImplement.Models.Zakupka", "zakupka")
                        .WithOne("complect")
                        .HasForeignKey("ComputerShopDataBaseImplement.Models.Complect", "ComplectId");

                    b.HasOne("ComputerShopDataBaseImplement.Models.Postavshik", "postavshik")
                        .WithMany("Complects")
                        .HasForeignKey("PostavshikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("postavshik");

                    b.Navigation("zakupka");
                });

            modelBuilder.Entity("ComputerShopDataBaseImplement.Models.ComplectPolTechnic", b =>
                {
                    b.HasOne("ComputerShopDataBaseImplement.Models.Complect", "complect")
                        .WithMany("ComplectPolTechnic")
                        .HasForeignKey("ComplectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ComputerShopDataBaseImplement.Models.PolTechnic", "poltechnic")
                        .WithMany("ComplectPolTechnic")
                        .HasForeignKey("PolTechnicId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("complect");

                    b.Navigation("poltechnic");
                });

            modelBuilder.Entity("ComputerShopDataBaseImplement.Models.Sborka", b =>
                {
                    b.HasOne("ComputerShopDataBaseImplement.Models.Postavshik", "postavshik")
                        .WithMany("Sborkas")
                        .HasForeignKey("PostavshikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("postavshik");
                });

            modelBuilder.Entity("ComputerShopDataBaseImplement.Models.SborkaComplect", b =>
                {
                    b.HasOne("ComputerShopDataBaseImplement.Models.Complect", "complect")
                        .WithMany("SborkaComplect")
                        .HasForeignKey("ComplectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ComputerShopDataBaseImplement.Models.Sborka", "sborka")
                        .WithMany("SborkaComplect")
                        .HasForeignKey("SborkaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("complect");

                    b.Navigation("sborka");
                });

            modelBuilder.Entity("ComputerShopDataBaseImplement.Models.SborkaZaiavka", b =>
                {
                    b.HasOne("ComputerShopDataBaseImplement.Models.Sborka", "sborka")
                        .WithMany("SborkaZaiavkas")
                        .HasForeignKey("SborkaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ComputerShopDataBaseImplement.Models.Zaiavka", "zaiavka")
                        .WithMany("SborkaZaiavka")
                        .HasForeignKey("ZaiavkaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("sborka");

                    b.Navigation("zaiavka");
                });

            modelBuilder.Entity("ComputerShopDataBaseImplement.Models.Zakupka", b =>
                {
                    b.HasOne("ComputerShopDataBaseImplement.Models.Postavshik", "postavshik")
                        .WithMany("Zakupkas")
                        .HasForeignKey("PostavshikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerShopDataBaseImplement.Models.Postavka", "postavka")
                        .WithOne("zakupka")
                        .HasForeignKey("ComputerShopDataBaseImplement.Models.Zakupka", "ZakupkaId");

                    b.Navigation("postavka");

                    b.Navigation("postavshik");
                });

            modelBuilder.Entity("ComputerShopDataBaseImplement.Models.Complect", b =>
                {
                    b.Navigation("ComplectPolTechnic");

                    b.Navigation("SborkaComplect");
                });

            modelBuilder.Entity("ComputerShopDataBaseImplement.Models.PolTechnic", b =>
                {
                    b.Navigation("ComplectPolTechnic");
                });

            modelBuilder.Entity("ComputerShopDataBaseImplement.Models.Postavka", b =>
                {
                    b.Navigation("zakupka");
                });

            modelBuilder.Entity("ComputerShopDataBaseImplement.Models.Postavshik", b =>
                {
                    b.Navigation("Complects");

                    b.Navigation("Sborkas");

                    b.Navigation("Zakupkas");
                });

            modelBuilder.Entity("ComputerShopDataBaseImplement.Models.Sborka", b =>
                {
                    b.Navigation("SborkaComplect");

                    b.Navigation("SborkaZaiavkas");
                });

            modelBuilder.Entity("ComputerShopDataBaseImplement.Models.Zaiavka", b =>
                {
                    b.Navigation("SborkaZaiavka");
                });

            modelBuilder.Entity("ComputerShopDataBaseImplement.Models.Zakupka", b =>
                {
                    b.Navigation("complect");
                });
#pragma warning restore 612, 618
        }
    }
}
